# --- build stage ---
FROM golang:1.26-alpine AS builder

WORKDIR /app


COPY parser/go.mod parser/go.sum ./
RUN go mod download


COPY parser/ .


RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o parser ./cmd

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/parser .

RUN mkdir -p /app/data

EXPOSE 8080

CMD ["./parser"]